devexperts/dx-platform

packages/react-kit/src/components/Popover/Popover.tsx

Reverts devex-web-frontend/dx-platform#2

Revert "bugfix/Popover-close-on-scroll | fixes"

---

package.json
packages/react-kit/package-lock.json
packages/react-kit/package.json
packages/react-kit/src/components/BoundsUpdateDetector/BoundsUpdateDetector.tsx
packages/react-kit/src/components/Popover/Popover.tsx
packages/react-kit/src/components/Popup/Popup.page.tsx
packages/react-kit/src/components/Popup/Popup.tsx
packages/react-kit/src/components/Scrollbar/HorizontalScrollbar.tsx
packages/react-kit/src/components/Scrollbar/Scrollbar.tsx
packages/react-kit/src/components/ToggleButtons/ToggleButtons.tsx
packages/react-kit/src/components/input/Input.tsx
packages/react-kit/src/utils/withTheme.ts
packages/react-kit/tsconfig.json
packages/tools/package-lock.json
packages/tools/package.json

React is now 16.3.1,
TS: 2.8.1, `strictNullChecks` in turned on. 
Adding `strictFunctionTypes` flag requires additional work with some components. I think this is to be implemented under a separate issue.

update versions of react and react-dom to 16.3.1 and ts to 2.8.1

---

packages/react-kit/src/components/Button/Button.page.tsx
packages/react-kit/src/components/Checkbox/Checkbox.page.tsx
packages/react-kit/src/components/Checkbox/Checkbox.tsx
packages/react-kit/src/components/DefaultTheme/DefaultTheme.tsx
packages/react-kit/src/components/Deferred/Deferred.tsx
packages/react-kit/src/components/EventListener/EventListener.tsx
packages/react-kit/src/components/LoadingIndicator/LoadingIndicator.page.tsx
packages/react-kit/src/components/LoadingIndicator/LoadingIndicator.tsx
packages/react-kit/src/components/Popup/Popup.page.tsx
packages/react-kit/src/components/Popup/Popup.tsx
packages/react-kit/src/components/Scrollable/Scrollable.const.ts
packages/react-kit/src/components/Scrollable/Scrollable.tsx
packages/react-kit/src/components/Scrollbar/Bar.tsx
packages/react-kit/src/components/Scrollbar/VerticalScrollbar.tsx
packages/react-kit/src/components/ToggleButtons/ToggleButtons.tsx
packages/react-kit/src/utils/withTheme.ts
packages/react-kit/tsconfig.json

react-kit's tsconfig.json contained `noUnusedLocals: false`. Removed it

removed "noUnusedLocals: false" from tsconfig. fixed errors

---

.travis.yml
package.json
packages/react-kit/package.json
packages/react-kit/src/components/Button/Button.tsx
packages/tools/src/scripts/build-lib.ts
packages/tools/src/tasks/ts-transform.ts
readme.md

This PR adds build settings for Travis CI. Relevant to #10 
A lot of trash in commits (I was testing Travis), they'd better be squashed

Build settings for travis ci

---

packages/react-kit/src/utils/with-rx.ts

Attempt to fix #16 .
Maybe need to think about tests for this :)

with-rx | expose effects stream from selector

---

packages/react-kit/src/components/render-remote-data/demo/render-remote-data.page.tsx
packages/react-kit/src/components/render-remote-data/get-render-remote-data.ts
packages/react-kit/src/components/render-remote-data/render-remote-data.component.tsx

implements component RenderRemoteData and the factory for it

Implement render remote data

---

packages/react-kit/src/components/Popover/Popover.tsx

- if statement to filter scroll event from strange scroll listener

Close popover on scroll

---

packages/rx-utils/src/create-handler.utils.ts

make creating subjects and function to next to it easier

feat: add create handler

---

packages/react-kit/src/components/Popover/Popover.page.styl
packages/react-kit/src/components/Popover/Popover.page.tsx
packages/react-kit/src/components/Popover/Popover.tsx
packages/tools/package.json
yarn.lock

fix(react-kit): fix popover closing on scroll inside

---

packages/react-kit/src/components/Scrollable/Scrollable.styl
packages/react-kit/src/components/Scrollbar/HorizontalScrollbar.tsx
packages/react-kit/src/components/Scrollbar/Scrollbar.demo.styl
packages/react-kit/src/components/Scrollbar/Scrollbar.util.ts
packages/react-kit/src/components/Scrollbar/VerticalScrollbar.tsx

Fix for https://github.com/devex-web-frontend/dx-platform/issues/82

fix(react-kit): Scrollable incorrectly sets content padding in Chrome and IE/FF

---

packages/react-kit/src/components/Scrollable/Scrollable.page.styl
packages/react-kit/src/components/Scrollable/Scrollable.page.tsx
packages/react-kit/src/components/Scrollable/Scrollable.styl
packages/react-kit/src/components/Scrollable/Scrollable.tsx

Closes https://github.com/devex-web-frontend/dx-platform/issues/79
Tested in IE 11, Edge, Firefox, Chrome, Safari.

feat(react-kit): Added ability to display content under scrollbars

---

packages/rx-utils/src/__tests__/context.utils.spec.ts
packages/rx-utils/src/context.utils.ts

closes #108 
BREAKING CHANGE: Context is not a ProductLeft anymore

fix(rx-utils): fix combineContext to subscribe to Sink returned from project

---

packages/rx-utils/src/rd/entity-store.utils.ts

added some basic information for entity-store

feat(rx-utils): added methods annotation for entity-store

---

.vscode/settings.json
packages/react-kit/src/utils/with-rx2.ts

Remove default AnimationFrameScheduler from withRX2

---

package.json
packages/lint/LICENSE
packages/lint/README.md
packages/lint/package.json
packages/react-kit/LICENSE
packages/react-kit/README.md
packages/react-kit/package.json
packages/rx-utils/LICENSE
packages/rx-utils/README.md
packages/rx-utils/package.json
packages/tools/LICENSE
packages/tools/README.md
packages/tools/package.json
packages/utils/LICENSE
packages/utils/README.md
packages/utils/package.json
readme.md

- adding license files to each package
- update metadata inside `package.json` in each package after organisation migration

Housekeeping after repo migration

---

.commitlintrc.json
.travis.yml
package.json
yarn.lock

build: integrate commitlint

---

.travis.yml
package.json
packages/react-kit/package.json
yarn.lock

This PR adds an ability to manually deploy storybook to gh-pages: https://devexperts.github.io/dx-platform .

ci: add scripts for storybook deployment

---

.travis.yml

ci: make a travis check stricter (#174)

---

packages/react-kit/src/components/Selectbox/Selectbox.page.tsx
packages/react-kit/src/components/Selectbox/Selectbox.tsx
packages/react-kit/src/components/Selectbox/SelectboxAnchor.tsx

This is a (correct, not like #172 ) porting PR for #121
@scink since you were the approver for the original one, could you approve this one as well? It looks exactly the same as the previous one, but we are required to have approval by the process :)

feat(react-kit): Selectbox. (correct) Multiselect feature porting

---

packages/rx-utils/src/__tests__/create-handler.utils.spec.ts
packages/rx-utils/src/create-handler.utils.ts

fix(rx-utils): createHandler union types fix

---

yarn.lock

Revert "chore: yarn upgrade lerna"

---

packages/react-kit/package.json
packages/react-kit/src/utils/use-observable.ts
packages/react-kit/src/utils/use-subscription.ts
packages/rx-utils/package.json
packages/rx-utils/src/live-data.utils.ts
packages/rx-utils/src/observable-map.utils.ts
packages/rx-utils/src/observable.utils.ts
packages/rx-utils/src/rd/__tests__/entity-store.utils.test.ts
packages/rx-utils/src/rd/entity-store.utils.ts
yarn.lock

This PR contains several features and fixes to react-kit and rx-utils

---

packages/react-kit/src/utils/use-sink.ts
packages/rx-utils/src/live-data.utils.ts
packages/rx-utils/src/sink2.utils.ts
packages/utils/src/adt/live-data.utils.ts
packages/utils/src/adt/sink.utils.ts
packages/utils/src/typeclasses/foldable-value/foldable-value.ts

BREAKING CHANGE: fixed typo in rx-utils LiveData URI
Includes changes from https://github.com/devexperts/dx-platform/pull/209

feat(utils, rx-utils): abstract LiveData from Observable and RemoteData

---

packages/react-kit/src/components/EventListener/EventListener.tsx
packages/react-kit/src/components/RootClose/RootClose.tsx

Instead of https://github.com/devexperts/dx-platform/pull/212

fix(react-kit): fixed big with selectbox
